[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
soft-wrap.enable = true
